version: '3.9'
services: 
  mongodb:
    container_name: db-customers
    image: mongo
    hostname: host-bank
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hrevilla
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - data-customers:/data/db
    networks:
      - bank
  ms-customers:
    ports:
      - "8081:8081"
    networks:
      - bank
    depends_on:
      - mongodb

volumes:
  data-customers:
    name: data-customers

networks:
  bank:
    name: bank